executable = /bin/bash 
arguments = -i conda.sh tf main.py                  # change name of conda environment
log = logfile.log 
transfer_input_files = /home/user/scripts/conda.sh, main.py, /home/user/scripts/generate_data.py
output = stdout.txt 
error = stderr.txt 
stream_output = True
stream_error = True
should_transfer_files = IF_NEEDED 
request_gpus = 1
#request_disk = 180 GB
#request_memory = 40000 MB
#requirements = ((TARGET.Machine =="pascal-node05.l3s.intra") || (TARGET.Machine == "pascal-node06.l3s.intra") || (TARGET.Machine == "pascal-node07.l3s.intra") || (TARGET.Machine == "pascal-node08.l3s.intra"))
queue
